### ISSUE TITLE
create two icons launch app

### ISSUE THREAD

**Issue by nelsongc** [maxyou/CalendarPicker#1]
after add library on my app, it has two icons to launch app,
one open sample of calendar
and other open my app

when I remove intent-filter from my main activity open calendar activity sample, this is the log

$ adb shell am start -n "com........../com.maxproj.calendarpicker.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER

**Comment by maxyou** [comment]
Thanks for your issue!
I had just remove the intent filter which create no needed launch icon. Can you try it again?
Please update version number to 1.1.2
