### ISSUE TITLE
setMinDate function.

### ISSUE THREAD

**Issue by GouravdeepSingh** [maxyou/CalendarPicker#2]
It is a great library. but it lose some functionality like setMinDate of DatePickerDialog.

**Comment by maxyou** [comment]
The min date means the first day that can be picked?

**Comment by GouravdeepSingh** [comment]
yes, the first day that can be picked. And all dates before that day are disabled.

**Comment by GouravdeepSingh** [comment]
And there is one bug. Open picker through a fragment and then press back, picker is not closed, but fragment is closed.

**Comment by maxyou** [comment]
Your suggestion is very good, thanks. But this time I do not have time to add this kind of feature. I hope user compare the picked time with his min date and return "pick error" as a workaround.

The bug that press back cause fragment be closed, which I just test it, but did not appeared. I open a test proj with its apk at: https://github.com/maxyou/TestOpenCalendarFromFragment

Would you mind compare my code with your code that can produce this bug? thanks.

**Comment by GouravdeepSingh** [comment]
The bug that press back cause fragment be closed:-- Please check this in Android Navigation Architecture Components.
